# Generated by Django 4.1.2 on 2022-10-18 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestlist',
            name='title',
        ),
    ]
