# Generated by Django 4.1.2 on 2022-10-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist_app', '0002_guestlists_guests_delete_guestlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestLists',
            new_name='GuestList',
        ),
        migrations.AlterModelOptions(
            name='guestlist',
            options={'verbose_name_plural': 'Guestlists'},
        ),
        migrations.AlterModelOptions(
            name='guests',
            options={'verbose_name_plural': 'Guests'},
        ),
    ]
